# Generated by Django 4.2.1 on 2023-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0004_yourstory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourstory',
            name='caption',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
